#!/usr/bin/env bash

DOTFILES="dansomething/dotfiles"
DOTVIM="https://github.com/dansomething/dot_vim.git"
VUNDLE="http://github.com/gmarik/vundle.git"

# Detect the OS platform
unamestr=$(uname)
case "$unamestr" in
    Darwin) PLATFORM='osx' ;;
    Linux) PLATFORM='linux' ;;
    *) PLATFORM='windows' ;;
esac
unset unamestr

if [[ "$PLATFORM" == 'osx' ]]; then
  # Check for Homebrew
  if test ! $(which brew); then
    echo " Installing Homebrew"
    ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"

    if test ! $(which git); then
      echo " Installing git"
      brew install git
    fi
  else
    echo " + Homebrew found."
  fi
fi

# Check for required commands...
# TODO Remove the dependency on gem
CMDS="gem git vim"
for cmd in $CMDS; do
    type -P $cmd &>/dev/null && continue || { echo "$cmd command not found. Please install $cmd."; exit 1; }
done

# Install required gems...
# TODO Remove the dependency on rake
GEMS="rake"
for gem in $GEMS; do
    found=`gem list $gem | grep -i $gem`
    if [ "$found" != "" ]; then
        parts=( $found )
        echo "Found ${parts[0]} ${parts[1]}"
        continue
    fi

    echo "---------------------------"
    echo "Installing $gem"
    sudo gem install $gem
    echo "---------------------------"
done

# Install Homeshick
curl -sL https://raw.github.com/andsens/homeshick/master/install.sh | bash

# Install dotfiles
~/.homeshick clone $DOTFILES
~/.homeshick symlink dotfiles

# Install dot_vim + vundle
# .vim should be pulled as a submodule of the dotfiles
cd ~/.vim
git clone $VUNDLE bundle/vundle
rake vim:link
vim +BundleInstall +qall
