#!/usr/bin/env sh

DOTFILES="dansomething/dotfiles"
DOTVIM="http://github.com/gmarik/vundle.git"

# Install required gems
GEMS=( homesick )
for gem in "${GEMS[@]}"; do
  found=`gem list $gem | grep -i $gem`
  if [ "$found" != "" ]; then
    parts=( $found )
    echo "Found ${parts[0]} ${parts[1]}"
    continue
  fi

  echo "---------------------------"
  echo "Installing $gem"
  sudo gem install $gem -y
  echo "---------------------------"
done

# Install dotfiles
homesick clone $DOTFILES
homesick symlink $DOTFILES

# Install dot_vim + vundle
cd ~/.vim
git clone $DOTVIM bundle/vundle
rake vim:link
vim +BundleInstall +qall