#!/usr/bin/env bash

DOTFILES="dansomething/dotfiles"
DOTVIM="https://github.com/dansomething/dot_vim.git"
VUNDLE="http://github.com/gmarik/vundle.git"

# Check for required commands...
CMDS="gem"
for cmd in $CMDS; do
    type -P $cmd &>/dev/null && continue || { echo "$cmd command not found. Please install $cmd."; exit 1; }
done

# Install required gems...
GEMS="rake json homesick"
for gem in $GEMS; do
    found=`gem list $gem | grep -i $gem`
    if [ "$found" != "" ]; then
        parts=( $found )
        echo "Found ${parts[0]} ${parts[1]}"
        continue
    fi

    echo "---------------------------"
    echo "Installing $gem"
    sudo gem install $gem -y
    echo "---------------------------"
done

# Install dotfiles
homesick clone $DOTFILES
homesick symlink $DOTFILES

# Install dot_vim + vundle
# .vim should be pulled as a submodule of the dotfiles
cd ~/.vim
git clone $VUNDLE bundle/vundle
rake vim:link
vim +BundleInstall +qall
