#!/bin/bash

##
# Script to start and stop all services
# required for development
#
# Author: dhansen 2009-08-25
##

##
# Configurable options
##

##
# Functions to manage the services
##
start_services()
{
	nexus start
	sudo mysql-server start
}

stop_services()
{
	nexus stop
	sudo mysql-server stop
}

##
# Output the usage information and exit
##
options_usage()
{
	cat <<-USAGE_END
		Usage: `basename $0` {start|stop}
		
		Options:
		  -h        Display help information

		Services:
		  Nexus
		  MySQL

USAGE_END
	exit 1
}

##
# Script 'main'
##

# Parse command options
while getopts "d P: h" option 
do
	case "$option" in
		h) options_usage ;;
		*) options_usage ;;
	esac
done

##
# Execute the commands to start the services
##
case "$1" in
	start) start_services ;;
	stop) stop_services ;;
	*) options_usage ;;
esac
