# https://alacritty.org/config-alacritty.html
# Colors (Jellybeans)
[colors.bright]
black = "0xc8c8c8"
blue = "0xbddff7"
cyan = "0x0bbdb6"
green = "0xc8e2b9"
magenta = "0xfce2ff"
red = "0xffb2b0"
white = "0xfeffff"
yellow = "0xffe1af"

[colors.cursor]
cursor = "0xffb472"
text = "0xfeffff"

[colors.normal]
black = "0xa3a3a3"
blue = "0xa6cae2"
cyan = "0x00a69f"
green = "0xa3c38b"
magenta = "0xe7cdfb"
red = "0xe98885"
white = "0xe4e4e4"
yellow = "0xffc68d"

[colors.primary]
background = "0x151515"
foreground = "0xe8e8d3"

[colors.selection]
background = "0xf6f6f6"
text = "0x5963a2"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[terminal.shell]
args = ["-S", "bash", "-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/env"

[window]
option_as_alt = "Both"
startup_mode = "Fullscreen"

[terminal]
